### ISSUE TITLE
adding setup.py & pypi release

### ISSUE THREAD

**Issue by vitkl** [KrishnaswamyLab/AAnet#1]
Hi David,

Thanks for your effort of improving archetypal analysis. I would like to use this package so I am wondering if you plan to release it via pypi. If not any time soon, would it be posible for you to add setup.py so that AAnet can be installed via pip? E.g. `pip install git+https://github.com/KrishnaswamyLab/AAnet.git`).

**Comment by dvdijk** [comment]
We would like to release it via pypi but probably not anytime soon.
I'll add setup.py though

**Comment by vitkl** [comment]
Thanks, that would be quite helpful. If I am not wrong you would need to put your *.py scripts in the subfolder to group them into one module.

Not related, but could you clarify whether your code is using gaussian error model? If so, can the transformation that network makes account for the mean-variance dependence of the scRNA-seq data?
